#1 1 * * * root ckan --plugin=ckanext-geodatagov geodatagov clean-deleted -c /etc/ckan/production.ini >> /var/log/clean_deleted.log 2>&1
#1 3 * * * root ckan tracking update >> /var/log/ckan_tracking.log 2>&1
#30 23 * * * root supervisorctl start qa-update-sel:*

- name: "ckan --plugin=ckanext-geodatagov geodatagov clean-deleted -c /etc/ckan/production.ini >> /var/log/clean_deleted.log 2>&1"
  cron:
    name: "clean-deleted"
    hour: "1"
    minute: "1"
    job: "ckan --plugin=ckanext-geodatagov geodatagov clean-deleted -c /etc/ckan/production.ini >> /var/log/clean_deleted.log 2>&1"
    user: ckan

- name: "ckan tracking update >> /var/log/ckan_tracking.log 2>&1"
  cron:
    name: "tracking update"
    hour: "1"
    minute: "3"
    job: "ckan tracking update >> /var/log/ckan_tracking.log 2>&1"
    user: ckan

- name: "supervisorctl start qa-update-sel:*"
  cron:
    name: "supervisorctl start qa-update-sel:*"
    hour: "23"
    minute: "30"
    job: "supervisorctl start qa-update-sel:*"
    user: ckan

#30 7 * * * root supervisorctl stop qa-update-sel:*
#0 6 * * * root ckan --plugin=ckanext-report report generate >> /var/log/ckan_report.log 2>&1
#0 5 * * 0 root ckan --plugin=ckanext-geodatagov geodatagov db_solr_sync >> /var/log/db_solr_sync.log 2>&1

- name: "supervisorctl stop qa-update-sel:*"
  cron:
    name: "supervisorctl stop qa-update-sel:*"
    hour: "7"
    minute: "30"
    job: "supervisorctl stop qa-update-sel:*"
    user: ckan

- name: "ckan --plugin=ckanext-report report generate >> /var/log/ckan_report.log 2>&1"
  cron:
    name: "ckanext-report report generate"
    hour: "6"
    minute: "0"
    job: "ckan --plugin=ckanext-report report generate >> /var/log/ckan_report.log 2>&1"
    user: ckan

- name: "ckan --plugin=ckanext-geodatagov geodatagov db_solr_sync >> /var/log/db_solr_sync.log 2>&1"
  cron:
    name: "ckanext-geodatagov geodatagov"
    weekday: "0"
    hour: "6"
    minute: "0"
    job: "ckan --plugin=ckanext-geodatagov geodatagov db_solr_sync >> /var/log/db_solr_sync.log 2>&1"
    user: ckan

#30 5 * * * root ckan --plugin=ckanext-geodatagov geodatagov harvest-job-cleanup >> /var/log/harvest_job_cleanup.log 2>&1
#30 4 * * * root ckan --plugin=ckanext-geodatagov geodatagov combine-feeds >> /var/log/ckan-combine-feeds.log 2>&1
#2 2 * * * root ckan --plugin=ckanext-geodatagov geodatagov export-csv >> /var/log/ckan-export-csv.log 2>&1
#0 5 * * * root ckan --plugin=ckanext-geodatagov geodatagov sitemap-to-s3 >> /var/log/sitemap-to-s3.log 2>&1

- name: "ckan --plugin=ckanext-geodatagov geodatagov harvest-job-cleanup >> /var/log/harvest_job_cleanup.log 2>&1"
  cron:
    name: "ckanext-geodatagov geodatagov harvest-job-cleanup"
    hour: "5"
    minute: "30"
    job: "ckan --plugin=ckanext-geodatagov geodatagov harvest-job-cleanup >> /var/log/harvest_job_cleanup.log 2>&1"
    user: ckan

- name: "ckan --plugin=ckanext-geodatagov geodatagov combine-feeds >> /var/log/ckan-combine-feeds.log 2>&1"
  cron:
    name: "ckanext-geodatagov geodatagov combine-feeds"
    hour: "4"
    minute: "30"
    job: "ckan --plugin=ckanext-geodatagov geodatagov combine-feeds >> /var/log/ckan-combine-feeds.log 2>&1"
    user: ckan

- name: "ckan --plugin=ckanext-geodatagov geodatagov export-csv >> /var/log/ckan-export-csv.log 2>&1"
  cron:
    name: "ckanext-geodatagov geodatagov export-csv"
    hour: "2"
    minute: "2"
    job: "ckan --plugin=ckanext-geodatagov geodatagov export-csv >> /var/log/ckan-export-csv.log 2>&1"
    user: ckan

- name: "ckan --plugin=ckanext-geodatagov geodatagov sitemap-to-s3 >> /var/log/sitemap-to-s3.log 2>&1"
  cron:
    name: "ckanext-geodatagov geodatagov sitemap-to-s3"
    hour: "5"
    minute: "0"
    job: "ckan --plugin=ckanext-geodatagov geodatagov sitemap-to-s3 >> /var/log/sitemap-to-s3.log 2>&1"
    user: ckan

## jsonl export on 3rd day of each month at 2:01 AM
#1 2 3 * * root ckan --plugin=ckanext-geodatagov geodatagov jsonl-export >> /var/log/jsonl-export.log 2>&1

- name: "ckan --plugin=ckanext-geodatagov geodatagov jsonl-export >> /var/log/jsonl-export.log 2>&1"
  cron:
    name: "ckanext-geodatagov geodatagov jsonl-export"
    day: "3"
    hour: "2"
    minute: "1"
    job: "ckan --plugin=ckanext-geodatagov geodatagov jsonl-export >> /var/log/jsonl-export.log 2>&1"
    user: ckan
